config/routes.rb
get 'oauth_azure', :to => 'redmine_oauth#oauth_azure'
get 'oauth2callback_azure', :to => 'redmine_oauth#oauth_azure_callback', :as => 'oauth_azure_callback'

app/controllers/redmine_oauth_controller.rb
require 'account_controller'
require 'json'
require 'jwt'

class RedmineOauthController < AccountController
  include Helpers::MailHelper
  include Helpers::Checker
  def oauth_azure
    if Setting.plugin_redmine_omniauth_azure['azure_oauth_authentication']
      session['back_url'] = params['back_url']
      if Setting.plugin_redmine_omniauth_azure['redirect_uri'] && !Setting.plugin_redmine_omniauth_azure['redirect_uri'].empty?
		redirect_to oauth_client.auth_code.authorize_url(:redirect_uri => Setting.plugin_redmine_omniauth_azure['redirect_uri'], :scope => scopes)
	  else
		redirect_to oauth_client.auth_code.authorize_url(:redirect_uri => oauth_azure_callback_url, :scope => scopes)
	  end
    else
      password_authentication
    end
  end

  def oauth_azure_callback
    if params['error']
      flash['error'] = l(:notice_access_denied)
      redirect_to signin_path
    else
      if Setting.plugin_redmine_omniauth_azure['redirect_uri'] && !Setting.plugin_redmine_omniauth_azure['redirect_uri'].empty?
			token = oauth_client.auth_code.get_token(params['code'], :redirect_uri => Setting.plugin_redmine_omniauth_azure['redirect_uri'], :resource => "00000002-0000-0000-c000-000000000000")
      else
			token = oauth_client.auth_code.get_token(params['code'], :redirect_uri => oauth_azure_callback_url, :resource => "00000002-0000-0000-c000-000000000000")
	  end
	  user_info = JWT.decode(token.token, nil, false)
      logger.error user_info
      
      email = user_info.first['unique_name']

      if email
        checked_try_to_login email, user_info.first
      else
        flash['error'] = l(:notice_no_verified_email_we_could_use)
        redirect_to signin_path
      end
    end
  end

  def checked_try_to_login(email, user)
    if allowed_domain_for?(email)
      try_to_login email, user
    else
      flash['error'] = l(:notice_domain_not_allowed, :domain => parse_email(email)['domain'])
      redirect_to signin_path
    end
  end

  def try_to_login email, info
    params['back_url'] = session['back_url']
    session.delete(:back_url)

    user = User.joins(:email_addresses)
               .where('email_addresses.address' => email, 'email_addresses.is_default' => true)
               .first_or_initialize
    if user.new_record?
      # Self-registration off
      # redirect_to(home_url) && return unless Setting.self_registration?
      # Create on the fly
      user.firstname, user.lastname = info["name"].split(' ') unless info['name'].nil?
      user.firstname ||= info["name"]
      user.lastname ||= info["name"]
      user.mail = email
      user.login = info['login']
      user.login ||= [user.firstname, user.lastname]*"."
      user.random_password
      user.register

      register_automatically(user)

      # case Setting.self_registration
      # when '1'
      #   register_by_email_activation(user) do
      #     onthefly_creation_failed(user)
      #   end
      # when '3'
      #   register_automatically(user) do
      #     onthefly_creation_failed(user)
      #   end
      # else
      #   register_manually_by_administrator(user) do
      #     onthefly_creation_failed(user)
      #   end
      # end
    else
      # Existing record
      if user.active?
        successful_authentication(user)
      else
        account_pending
      end
    end
  end

  def oauth_client
    @client ||= OAuth2::Client.new(settings['client_id'], settings['client_secret'],
      :site => 'https://login.windows.net',
      :authorize_url => '/' + settings['tenant_id'] + '/oauth2/authorize',
      :token_url => '/' + settings['tenant_id'] + '/oauth2/token')
  end

  def settings
    @settings ||= Setting.plugin_redmine_omniauth_azure
  end

  def scopes
    'user:email'
  end
end

app/helpers/redmine_omniauth_helper.rb
module RedmineOmniauthHelper
end

app/views/hooks/_view_account_login_bottom.html.erb
<%= stylesheet_link_tag 'buttons', :plugin => 'redmine_omniauth_azure' %>

<% if Setting.plugin_redmine_omniauth_azure['azure_oauth_authentication'] %>
  <%= link_to oauth_azure_path(:back_url => back_url) do %>
    <%= button_tag :class => 'button-login' do %>
      <%= image_tag('/plugin_assets/redmine_omniauth_azure/images/azure_login_icon.png', :class => 'button-login-icon', :alt => l(:login_via_azure)) %>
      <%= content_tag :div, l(:login_via_azure), :class => 'button-login-text' %>
    <% end %>
  <% end %>
<% end %>

app/views/settings/_azure_settings.html.erb
<p>
  <label>Client ID:</label>
  <%= text_field_tag 'settings[client_id]', @settings['client_id'] %>
</p>
<p>
  <label>Client Secret:</label>
  <%= text_field_tag 'settings[client_secret]', @settings['client_secret'] %>
</p>
<p>
  <label>Tenant ID:</label>
  <%= text_field_tag 'settings[tenant_id]', @settings['tenant_id'] %>
</p>
<p>
  <label>Available domains</label>
  <%= text_area_tag "settings[allowed_domains]", @settings['allowed_domains'], :rows => 5 %>
</p>
<p>
  <label>Redirect uri</label>
  <%= text_field_tag 'settings[redirect_uri]', @settings['redirect_uri'] %>
</p>
<p>
  <label>Oauth authentication:</label>
  <%= check_box_tag "settings[azure_oauth_authentication]", true, @settings['azure_oauth_authentication'] %>
</p>